spring:
  application:
    name: perf-service
  profiles:
    include: liquibase, microservice
  liquibase:
    change-log: classpath:config/db/changelog/master.xml
    check-change-log-location: true
    drop-first: false
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
  h2:
    console:
      path: /h2-console
  datasource:
    continue-on-error: false
    max-active: 500
server:  
  undertow:
    worker-threads: 500
  port: ${PORT:2201}