spring:
  jpa:
    show-sql: false
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_ADDR}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver  
