spring:
  profiles:
    include: h2
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:${spring.application.name};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE    
