spring:
  application:
    name: perf-service
  profiles:
    include: liquibase, microservice
  liquibase:
    change-log: classpath:config/db/changelog/master.xml
    check-change-log-location: true
    drop-first: false
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 20
          lob:
            non_contextual_creation: true
        cache:
          use_query_cache: false
          use_second_level_cache: false
          use_structured_entries: false
          use_minimal_puts: false
  h2:
    console:
      path: /h2-console
  datasource:
    continue-on-error: false
    max-active: 500
server:  
  undertow:
    worker-threads: 500
  port: ${PORT:2201}