spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_ADDR}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver  
server:
  servlet:
    contextPath: ${CONTEXT_PATH:/api/perf}