swagger: '2.0'
info:
  description: REST API for Performance Service
  version: '1.0'
  termsOfService: 'http://www.karumien.com/terms/'
  contact:
    email: info@karumien.com
  title: Performance DB Test Service
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
basePath: /api/v1/perf
schemes:
  - http
paths:
  /test/{id}:
    get:
      summary: Execute work 
      description: Execute work identified by ID
      operationId: getWork
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          description: Sequence number of work indentification 
          type: integer
        - name: category
          in: query
          description: Optional category of algorithm 0-9
          required: false
          type: integer
          default: -1
        - name: nowork
          in: query
          description: Optional enable no work simulation 
          required: false
          type: boolean
        - name: delay
          in: query
          description: Optional enable delay in ms, default is 100ms
          required: false
          default: 100
          type: integer
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/PerfTestWork'
definitions:
  PerfTestWork:
    type: object
    description: Perfomance work description
    properties:
      id:
        type: integer
        description: ID of performance work
      category:
        type: integer
        description: 0-9 of specified algorithm
      start:
        type: string
        format: date-time
        description: Start of work
      end:
        type: string
        format: date-time
        description: End of work
      length:
        type: integer
        format: int64
        description: Length of work in ms
      result:
        type: string
        description: Return algorithm control value
    example:
      id: 1007
      category: 7
      date: '2017-07-21T17:32:28Z'
      end: '2017-07-21T17:32:32Z'
      result: '323/18'